<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>z-util</artifactId>
        <groupId>io.github.yuku123</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>z-util-expr</artifactId>
    <packaging>pom</packaging>
    <name>z-util :: expr (expression engine aggregator: EL/Groovy/JS/Lua/SQL)</name>
    <description>脚本表达式执行分支：JS、SQL、Groovy、Lua、EL</description>

    <modules>
        <module>z-util-expr-js</module>
        <module>z-util-expr-sql</module>
        <module>z-util-expr-groovy</module>
        <module>z-util-expr-lua</module>
        <module>z-util-expr-el</module>
    </modules>
</project>
