<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>z-util-serialize</artifactId>
        <groupId>io.github.yuku123</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>z-util-serialize-core</artifactId>
    <packaging>jar</packaging>
    <name>z-util :: serialize :: core (wire format + zero-copy + reflective + codec)</name>
    <dependencies>
        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-serialize-schema</artifactId>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
        </dependency>
    </dependencies>
</project>
