package io.zifu.z.serialize.codegen;

import io.zifu.z.serialize.annotation.FieldType;
import io.zifu.z.serialize.annotation.ZField;
import io.zifu.z.serialize.annotation.ZMap;
import io.zifu.z.serialize.annotation.ZMessage;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Collections;
import java.util.Set;

/**
 * 编译期注解处理器：为每个 {@code @ZMessage} 类生成零反射的 {@code Codec} 实现。
 *
 * <p>生成的类名为 {@code {ClassName}Codec}，放在相同包中。
 * 生成的类在 static initializer 中自动注册到 {@code CodecRegistry}。</p>
 *
 * <p>使用方式：在 Maven 中添加 codegen 依赖即可（配合 annotationProcessorPaths）。</p>
 *
 * @author zifang
 */
public class ZSerializeProcessor extends AbstractProcessor {

    private Filer filer;
    private Messager messager;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        this.filer = processingEnv.getFiler();
        this.messager = processingEnv.getMessager();
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Collections.singleton(ZMessage.class.getCanonicalName());
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.RELEASE_8;
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(ZMessage.class)) {
            if (!(element instanceof TypeElement)) continue;
            TypeElement typeElement = (TypeElement) element;

            try {
                generateCodec(typeElement);
            } catch (IOException e) {
                messager.printMessage(Diagnostic.Kind.ERROR,
                        "Failed to generate codec for " + typeElement.getQualifiedName() + ": " + e.getMessage(),
                        element);
            }
        }
        return true;
    }

    private void generateCodec(TypeElement typeElement) throws IOException {
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(typeElement).getQualifiedName().toString();
        String className = typeElement.getSimpleName().toString();
        String codecName = className + "Codec";
        String qualifiedCodecName = packageName.isEmpty() ? codecName : packageName + "." + codecName;

        ZMessage zMessage = typeElement.getAnnotation(ZMessage.class);

        // 收集字段信息
        List<FieldInfo> fields = collectFields(typeElement);

        JavaFileObject jfo = filer.createSourceFile(qualifiedCodecName, typeElement);
        try (PrintWriter w = new PrintWriter(jfo.openWriter())) {
            // package
            if (!packageName.isEmpty()) {
                w.println("package " + packageName + ";");
                w.println();
            }

            // imports
            w.println("import io.zifu.z.serialize.core.Codec;");
            w.println("import io.zifu.z.serialize.core.CodecRegistry;");
            w.println("import io.zifu.z.serialize.core.WireType;");
            w.println("import io.zifu.z.serialize.core.ZInput;");
            w.println("import io.zifu.z.serialize.core.ZOutput;");
            w.println("import java.io.ByteArrayInputStream;");
            w.println("import java.io.ByteArrayOutputStream;");
            w.println("import java.io.IOException;");
            w.println("import java.nio.charset.StandardCharsets;");
            w.println("import java.util.ArrayList;");
            w.println("import java.util.Collection;");
            w.println("import java.util.LinkedHashMap;");
            w.println("import java.util.Map;");
            w.println();

            // class declaration
            w.println("/**");
            w.println(" * Generated zero-reflection codec for {@link " + className + "}.");
            w.println(" * Schema ID: " + zMessage.id() + ", name: \"" + zMessage.name() + "\"");
            w.println(" *");
            w.println(" * <p>DO NOT EDIT — generated by z-util-serialize-codegen.</p>");
            w.println(" */");
            w.println("public final class " + codecName + " implements Codec {");
            w.println();
            w.println("    public static final " + codecName + " INSTANCE = new " + codecName + "();");
            w.println();
            w.println("    static {");
            w.println("        CodecRegistry.register(" + className + ".class, INSTANCE);");
            w.println("    }");
            w.println();

            // write method
            generateWriteMethod(w, className, fields);
            w.println();

            // read method
            generateReadMethod(w, className, fields);
            w.println();

            // helper: writeVarIntValue
            generateWriteVarIntHelper(w);
            w.println();

            // helper: writeCollection
            generateWriteCollectionHelper(w, className, fields);
            w.println();

            // helper: writeMap
            generateWriteMapHelper(w, className, fields);
            w.println();

            w.println("}");
        }

        messager.printMessage(Diagnostic.Kind.NOTE,
                "Generated codec: " + qualifiedCodecName + " (" + fields.size() + " fields)");
    }

    private List<FieldInfo> collectFields(TypeElement typeElement) {
        List<FieldInfo> fields = new ArrayList<>();
        for (Element enclosed : typeElement.getEnclosedElements()) {
            if (!(enclosed instanceof VariableElement)) continue;
            VariableElement ve = (VariableElement) enclosed;
            if (ve.getModifiers().contains(Modifier.STATIC)) continue;
            if (ve.getModifiers().contains(Modifier.TRANSIENT)) continue;

            ZField zField = ve.getAnnotation(ZField.class);
            if (zField == null) continue;

            FieldInfo fi = new FieldInfo();
            fi.name = ve.getSimpleName().toString();
            fi.id = zField.id();
            fi.fieldType = zField.type();
            fi.deprecated = zField.deprecated();
            fi.removed = zField.removed();
            fi.packed = zField.packed();
            fi.javaType = ve.asType().toString();

            // 判断是否为 Collection
            TypeMirror tm = ve.asType();
            fi.isCollection = isCollectionType(tm);
            fi.isMap = isMapType(tm);
            fi.isEnum = isEnumType(tm);
            fi.isZMessage = isZMessageType(tm);

            // 获取泛型参数
            if (fi.isCollection || fi.isMap) {
                fi.elementType = getCollectionElementType(tm);
                if (fi.isMap) {
                    fi.keyType = getMapKeyType(tm);
                }
            }

            fields.add(fi);
        }
        // 按 id 排序
        fields.sort((a, b) -> Integer.compare(a.id, b.id));
        return fields;
    }

    private boolean isCollectionType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return false;
        DeclaredType dt = (DeclaredType) tm;
        TypeElement te = (TypeElement) dt.asElement();
        String name = te.getQualifiedName().toString();
        return name.equals("java.util.List") || name.equals("java.util.ArrayList")
                || name.equals("java.util.Collection") || name.equals("java.util.LinkedList");
    }

    private boolean isMapType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return false;
        DeclaredType dt = (DeclaredType) tm;
        TypeElement te = (TypeElement) dt.asElement();
        String name = te.getQualifiedName().toString();
        return name.equals("java.util.Map") || name.equals("java.util.LinkedHashMap")
                || name.equals("java.util.HashMap");
    }

    private boolean isEnumType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return false;
        DeclaredType dt = (DeclaredType) tm;
        Element el = dt.asElement();
        return "ENUM".equals(el.getKind().name());
    }

    private boolean isZMessageType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return false;
        DeclaredType dt = (DeclaredType) tm;
        Element el = dt.asElement();
        return el.getAnnotation(ZMessage.class) != null;
    }

    private String getCollectionElementType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return "java.lang.Object";
        DeclaredType dt = (DeclaredType) tm;
        List<? extends TypeMirror> args = dt.getTypeArguments();
        if (args.isEmpty()) return "java.lang.Object";
        return args.get(0).toString();
    }

    private String getMapKeyType(TypeMirror tm) {
        if (!(tm instanceof DeclaredType)) return "java.lang.Object";
        DeclaredType dt = (DeclaredType) tm;
        List<? extends TypeMirror> args = dt.getTypeArguments();
        if (args.isEmpty()) return "java.lang.Object";
        return args.get(0).toString();
    }

    // ==================== Code Generation ====================

    private void generateWriteMethod(PrintWriter w, String className, List<FieldInfo> fields) {
        w.println("    @Override");
        w.println("    public void write(ZOutput out, Object message) throws IOException {");
        w.println("        " + className + " m = (" + className + ") message;");

        for (FieldInfo fi : fields) {
            if (!fi.removed.isEmpty()) continue;
            w.println();
            w.println("        // field " + fi.id + ": " + fi.name);

            if (fi.isCollection) {
                w.println("        if (m." + fi.name + " != null) {");
                w.println("            writeCollection_" + fi.name + "(out, m." + fi.name + ");");
                w.println("        }");
            } else if (fi.isMap) {
                w.println("        if (m." + fi.name + " != null) {");
                w.println("            writeMap_" + fi.name + "(out, m." + fi.name + ");");
                w.println("        }");
            } else {
                if (isPrimitive(fi.javaType)) {
                    writeFieldCode(w, "        ", fi, "m." + fi.name);
                } else {
                    w.println("        if (m." + fi.name + " != null) {");
                    writeFieldCode(w, "            ", fi, "m." + fi.name);
                    w.println("        }");
                }
            }
        }

        w.println("    }");
    }


    private void writeFieldCode(PrintWriter w, String indent, FieldInfo fi, String valueExpr) {
        switch (fi.fieldType) {
            case VARINT:
                if (fi.isEnum) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.VARINT);");
                    w.println(indent + "out.writeSignedVarInt((" + fi.javaType + ").ordinal());");
                } else if (fi.javaType.equals("boolean") || fi.javaType.equals("java.lang.Boolean")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.VARINT);");
                    w.println(indent + "out.writeVarInt(" + valueExpr + " ? 1 : 0);");
                } else if (fi.javaType.equals("int") || fi.javaType.equals("java.lang.Integer")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.VARINT);");
                    w.println(indent + "out.writeSignedVarInt(" + valueExpr + ");");
                } else if (fi.javaType.equals("long") || fi.javaType.equals("java.lang.Long")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.VARINT);");
                    w.println(indent + "out.writeSignedVarLong(" + valueExpr + ");");
                } else {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.VARINT);");
                    w.println(indent + "out.writeSignedVarInt(((Number)" + valueExpr + ").intValue());");
                }
                break;

            case FIXED32:
                if (fi.javaType.equals("float") || fi.javaType.equals("java.lang.Float")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.FIXED32);");
                    w.println(indent + "out.writeFloat(" + valueExpr + ");");
                } else {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.FIXED32);");
                    w.println(indent + "out.writeFixed32(((Number)" + valueExpr + ").intValue());");
                }
                break;

            case FIXED64:
                if (fi.javaType.equals("double") || fi.javaType.equals("java.lang.Double")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.FIXED64);");
                    w.println(indent + "out.writeDouble(" + valueExpr + ");");
                } else {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.FIXED64);");
                    w.println(indent + "out.writeFixed64(((Number)" + valueExpr + ").longValue());");
                }
                break;

            case LENGTH_DELIMITED:
                if (fi.javaType.equals("java.lang.String")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
                    w.println(indent + "out.writeLengthDelimited((" + valueExpr + ").getBytes(StandardCharsets.UTF_8));");
                } else if (fi.javaType.equals("byte[]")) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
                    w.println(indent + "out.writeLengthDelimited(" + valueExpr + ");");
                } else if (fi.isZMessage) {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
                    w.println(indent + "{");
                    w.println(indent + "    ByteArrayOutputStream _buf = new ByteArrayOutputStream(64);");
                    w.println(indent + "    ZOutput _nested = new ZOutput(_buf);");
                    w.println(indent + "    new " + fi.javaType + "Codec().write(_nested, " + valueExpr + ");");
                    w.println(indent + "    out.writeLengthDelimited(_buf.toByteArray());");
                    w.println(indent + "}");
                } else {
                    w.println(indent + "out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
                    w.println(indent + "out.writeLengthDelimited((" + valueExpr + ").toString().getBytes(StandardCharsets.UTF_8));");
                }
                break;
        }
    }

    private void generateWriteCollectionHelper(PrintWriter w, String className, List<FieldInfo> fields) {
        for (FieldInfo fi : fields) {
            if (!fi.isCollection || !fi.removed.isEmpty()) continue;

            w.println("    private void writeCollection_" + fi.name + "(ZOutput out, Collection<?> values) throws IOException {");
            if (fi.fieldType == FieldType.VARINT) {
                // packed encoding
                w.println("        ByteArrayOutputStream _packed = new ByteArrayOutputStream();");
                w.println("        ZOutput _p = new ZOutput(_packed);");
                w.println("        for (Object _v : values) {");
                String elemType = fi.elementType != null ? fi.elementType : "java.lang.Object";
                if (elemType.equals("int") || elemType.equals("java.lang.Integer")) {
                    w.println("            _p.writeSignedVarInt(((Integer) _v));");
                } else if (elemType.equals("long") || elemType.equals("java.lang.Long")) {
                    w.println("            _p.writeSignedVarLong(((Long) _v));");
                } else if (elemType.equals("boolean") || elemType.equals("java.lang.Boolean")) {
                    w.println("            _p.writeVarInt(((Boolean) _v) ? 1 : 0);");
                } else {
                    w.println("            writeVarIntValue(_p, _v);");
                }
                w.println("        }");
                w.println("        out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
                w.println("        out.writeLengthDelimited(_packed.toByteArray());");
            } else {
                // non-packed: write each element with the field's tag
                w.println("        for (Object _v : values) {");
                FieldInfo singleFi = new FieldInfo();
                singleFi.id = fi.id;
                singleFi.fieldType = fi.fieldType;
                singleFi.javaType = fi.elementType != null ? fi.elementType : "java.lang.Object";
                singleFi.isEnum = false;
                singleFi.isZMessage = false;
                writeFieldCode(w, "            ", singleFi, "_v");
                w.println("        }");
            }
            w.println("    }");
            w.println();
        }
    }

    private void generateWriteMapHelper(PrintWriter w, String className, List<FieldInfo> fields) {
        for (FieldInfo fi : fields) {
            if (!fi.isMap || !fi.removed.isEmpty()) continue;

            w.println("    private void writeMap_" + fi.name + "(ZOutput out, Map<?, ?> map) throws IOException {");
            w.println("        for (Map.Entry<?, ?> _e : map.entrySet()) {");
            w.println("            ByteArrayOutputStream _entry = new ByteArrayOutputStream(64);");
            w.println("            ZOutput _nested = new ZOutput(_entry);");
            // key
            w.println("            // key (field 1)");
            if (fi.keyType != null && fi.keyType.equals("java.lang.String")) {
                w.println("            _nested.writeTag(1, WireType.LENGTH_DELIMITED);");
                w.println("            _nested.writeLengthDelimited(_e.getKey().toString().getBytes(StandardCharsets.UTF_8));");
            } else {
                w.println("            _nested.writeTag(1, WireType.VARINT);");
                w.println("            _nested.writeSignedVarInt(((Number) _e.getKey()).intValue());");
            }
            // value
            w.println("            // value (field 2)");
            String valType = fi.elementType != null ? fi.elementType : "java.lang.Object";
            if (valType.equals("java.lang.String")) {
                w.println("            _nested.writeTag(2, WireType.LENGTH_DELIMITED);");
                w.println("            _nested.writeLengthDelimited(_e.getValue().toString().getBytes(StandardCharsets.UTF_8));");
            } else if (valType.equals("int") || valType.equals("java.lang.Integer")) {
                w.println("            _nested.writeTag(2, WireType.VARINT);");
                w.println("            _nested.writeSignedVarInt(((Number) _e.getValue()).intValue());");
            } else if (valType.equals("long") || valType.equals("java.lang.Long")) {
                w.println("            _nested.writeTag(2, WireType.VARINT);");
                w.println("            _nested.writeSignedVarLong(((Number) _e.getValue()).longValue());");
            } else if (valType.equals("boolean") || valType.equals("java.lang.Boolean")) {
                w.println("            _nested.writeTag(2, WireType.VARINT);");
                w.println("            _nested.writeVarInt(((Boolean) _e.getValue()) ? 1 : 0);");
            } else {
                w.println("            _nested.writeTag(2, WireType.VARINT);");
                w.println("            _nested.writeSignedVarInt(((Number) _e.getValue()).intValue());");
            }
            w.println("            out.writeTag(" + fi.id + ", WireType.LENGTH_DELIMITED);");
            w.println("            out.writeLengthDelimited(_entry.toByteArray());");
            w.println("        }");
            w.println("    }");
            w.println();
        }
    }

    private void generateReadMethod(PrintWriter w, String className, List<FieldInfo> fields) {
        w.println("    @Override");
        w.println("    @SuppressWarnings(\"unchecked\")");
        w.println("    public <T> T read(ZInput in, Class<T> messageClass) throws IOException {");
        w.println("        " + className + " m = new " + className + "();");
        w.println();
        w.println("        while (in.hasMore()) {");
        w.println("            int _tag = in.readTag();");
        w.println("            int _fid = ZInput.fieldId(_tag);");
        w.println("            int _wt = ZInput.wireTypeOf(_tag);");
        w.println();
        w.println("            switch (_fid) {");

        for (FieldInfo fi : fields) {
            if (!fi.removed.isEmpty()) continue;
            w.println("                case " + fi.id + ":");
            w.println("                    readField_" + fi.name + "(in, m, _wt);");
            w.println("                    break;");
        }

        w.println("                default:");
        w.println("                    skipUnknown(in, _wt);");
        w.println("                    break;");
        w.println("            }");
        w.println("        }");
        w.println();
        w.println("        return (T) m;");
        w.println("    }");
        w.println();

        // 生成每个字段的 read 方法
        for (FieldInfo fi : fields) {
            if (!fi.removed.isEmpty()) continue;
            generateReadFieldMethod(w, className, fi);
        }

        // skipUnknown
        w.println("    private static void skipUnknown(ZInput in, int wireType) throws IOException {");
        w.println("        switch (wireType) {");
        w.println("            case WireType.VARINT:          in.readVarInt(); break;");
        w.println("            case WireType.FIXED64:         in.readFixed64(); break;");
        w.println("            case WireType.FIXED32:         in.readFixed32(); break;");
        w.println("            case WireType.LENGTH_DELIMITED: in.skipLengthDelimited(); break;");
        w.println("            default: throw new IOException(\"Invalid wire type: \" + wireType);");
        w.println("        }");
        w.println("    }");
    }

    private void generateReadFieldMethod(PrintWriter w, String className, FieldInfo fi) {
        w.println("    private void readField_" + fi.name + "(ZInput in, " + className + " m, int wireType) throws IOException {");

        if (fi.isCollection) {
            w.println("        if (m." + fi.name + " == null) m." + fi.name + " = new ArrayList<>();");
            String elemType = fi.elementType != null ? fi.elementType : "java.lang.Object";
            if (fi.fieldType == FieldType.VARINT && fi.packed) {
                w.println("        if (wireType == WireType.LENGTH_DELIMITED) {");
                w.println("            byte[] _bytes = in.readLengthDelimited();");
                w.println("            ZInput _nested = new ZInput(new ByteArrayInputStream(_bytes));");
                w.println("            while (_nested.hasMore()) {");
                w.println("                m." + fi.name + ".add(" + readVarIntCast(elemType, "_nested") + ");");
                w.println("            }");
                w.println("        } else {");
                w.println("            m." + fi.name + ".add(" + readVarIntCast(elemType, "in") + ");");
                w.println("        }");
            } else {
                w.println("        m." + fi.name + ".add(" + readElementValue("in", fi, "wireType") + ");");
            }
            w.println("    }");
            w.println();
            return;
        }

        if (fi.isMap) {
            w.println("        if (m." + fi.name + " == null) m." + fi.name + " = new LinkedHashMap<>();");
            w.println("        byte[] _entryBytes = in.readLengthDelimited();");
            w.println("        ZInput _nested = new ZInput(new ByteArrayInputStream(_entryBytes));");
            w.println("        Object _key = null, _value = null;");
            w.println("        while (_nested.hasMore()) {");
            w.println("            int _eTag = _nested.readTag();");
            w.println("            int _eFid = ZInput.fieldId(_eTag);");
            w.println("            int _eWt = ZInput.wireTypeOf(_eTag);");
            w.println("            if (_eFid == 1) {");
            // key type
            String keyType = fi.keyType != null ? fi.keyType : "java.lang.Object";
            if (keyType.equals("java.lang.String")) {
                w.println("                _key = new String(_nested.readLengthDelimited(), StandardCharsets.UTF_8);");
            } else {
                w.println("                _key = (int) _nested.readSignedVarLong();");
            }
            w.println("            } else if (_eFid == 2) {");
            // value type
            String valType = fi.elementType != null ? fi.elementType : "java.lang.Object";
            if (valType.equals("java.lang.String")) {
                w.println("                _value = new String(_nested.readLengthDelimited(), StandardCharsets.UTF_8);");
            } else if (valType.equals("int") || valType.equals("java.lang.Integer")) {
                w.println("                _value = _nested.readSignedVarInt();");
            } else if (valType.equals("long") || valType.equals("java.lang.Long")) {
                w.println("                _value = _nested.readSignedVarLong();");
            } else if (valType.equals("boolean") || valType.equals("java.lang.Boolean")) {
                w.println("                _value = _nested.readVarInt() != 0;");
            } else {
                w.println("                _value = _nested.readSignedVarLong();");
            }
            w.println("            } else {");
            w.println("                skipUnknown(_nested, _eWt);");
            w.println("            }");
            w.println("        }");
            w.println("        m." + fi.name + ".put(_key, _value);");
            w.println("    }");
            w.println();
            return;
        }

        // 简单字段
        w.println("        Object _v;");
        switch (fi.fieldType) {
            case VARINT:
                if (fi.isEnum) {
                    w.println("        int _ord = in.readSignedVarInt();");
                    w.println("        _v = " + fi.javaType + ".values()[_ord];");
                } else if (fi.javaType.equals("boolean") || fi.javaType.equals("java.lang.Boolean")) {
                    w.println("        _v = in.readVarInt() != 0;");
                } else if (fi.javaType.equals("int") || fi.javaType.equals("java.lang.Integer")) {
                    w.println("        _v = in.readSignedVarInt();");
                } else if (fi.javaType.equals("long") || fi.javaType.equals("java.lang.Long")) {
                    w.println("        _v = in.readSignedVarLong();");
                } else {
                    w.println("        _v = in.readSignedVarInt();");
                }
                break;
            case FIXED32:
                if (fi.javaType.equals("float") || fi.javaType.equals("java.lang.Float")) {
                    w.println("        _v = in.readFloat();");
                } else {
                    w.println("        _v = in.readFixed32();");
                }
                break;
            case FIXED64:
                if (fi.javaType.equals("double") || fi.javaType.equals("java.lang.Double")) {
                    w.println("        _v = in.readDouble();");
                } else {
                    w.println("        _v = in.readFixed64();");
                }
                break;
            case LENGTH_DELIMITED:
                if (fi.javaType.equals("java.lang.String")) {
                    w.println("        _v = new String(in.readLengthDelimited(), StandardCharsets.UTF_8);");
                } else if (fi.javaType.equals("byte[]")) {
                    w.println("        _v = in.readLengthDelimited();");
                } else if (fi.isZMessage) {
                    w.println("        byte[] _bytes = in.readLengthDelimited();");
                    w.println("        _v = new " + fi.javaType + "Codec().read(new ZInput(new ByteArrayInputStream(_bytes)), " + fi.javaType + ".class);");
                } else {
                    w.println("        _v = new String(in.readLengthDelimited(), StandardCharsets.UTF_8);");
                }
                break;
            default:
                w.println("        _v = in.readSignedVarInt();");
                break;
        }
        w.println("        m." + fi.name + " = (" + fi.javaType + ") _v;");
        w.println("    }");
        w.println();
    }

    private String readVarIntCast(String type, String input) {
        if (type.equals("int") || type.equals("java.lang.Integer")) {
            return input + ".readSignedVarInt()";
        } else if (type.equals("long") || type.equals("java.lang.Long")) {
            return input + ".readSignedVarLong()";
        } else if (type.equals("boolean") || type.equals("java.lang.Boolean")) {
            return input + ".readVarInt() != 0";
        } else {
            return "(int) " + input + ".readSignedVarLong()";
        }
    }

    private String readElementValue(String input, FieldInfo fi, String wireTypeExpr) {
        switch (fi.fieldType) {
            case VARINT:
                return readVarIntCast(fi.elementType != null ? fi.elementType : "java.lang.Object", input);
            case FIXED32:
                return input + ".readFloat()";
            case FIXED64:
                return input + ".readDouble()";
            case LENGTH_DELIMITED:
                if (fi.elementType != null && fi.elementType.equals("java.lang.String")) {
                    return "new String(" + input + ".readLengthDelimited(), StandardCharsets.UTF_8)";
                }
                return input + ".readLengthDelimited()";
            default:
                return input + ".readSignedVarInt()";
        }
    }

    private void generateWriteVarIntHelper(PrintWriter w) {
        w.println("    private static void writeVarIntValue(ZOutput out, Object value) throws IOException {");
        w.println("        if (value instanceof Boolean) {");
        w.println("            out.writeVarInt(((Boolean) value) ? 1 : 0);");
        w.println("        } else if (value instanceof Integer) {");
        w.println("            out.writeSignedVarInt(((Integer) value));");
        w.println("        } else if (value instanceof Long) {");
        w.println("            out.writeSignedVarLong(((Long) value));");
        w.println("        } else if (value instanceof Enum) {");
        w.println("            out.writeSignedVarInt(((Enum<?>) value).ordinal());");
        w.println("        } else {");
        w.println("            out.writeSignedVarInt(((Number) value).intValue());");
        w.println("        }");
        w.println("    }");
    }

    private boolean isPrimitive(String javaType) {
        return "boolean".equals(javaType) || "int".equals(javaType)
                || "long".equals(javaType) || "double".equals(javaType)
                || "float".equals(javaType) || "short".equals(javaType)
                || "byte".equals(javaType) || "char".equals(javaType);
    }

    // ==================== FieldInfo ====================

    private static class FieldInfo {
        String name;
        int id;
        FieldType fieldType;
        boolean deprecated;
        String removed;
        boolean packed;
        String javaType;
        boolean isCollection;
        boolean isMap;
        boolean isEnum;
        boolean isZMessage;
        String elementType;
        String keyType;
    }
}
