<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>z-util</artifactId>
        <groupId>io.github.yuku123</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>z-util :: workflow (node-based workflow engine + Java/Python/Spark executors + BPMN model)</name>

    <artifactId>z-util-workflow</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-proxy</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-expr-js</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-expr-el</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-parser-json</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>