package com.zifang.util.monitor.exporter;

import com.zifang.util.core.lang.collection.Lists;
import com.zifang.util.monitor.MetricsRegistry;
import com.zifang.util.monitor.MetricsSnapshot;

import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * HTML 指标导出器
 * <p>
 * 生成 Druid 风格的 HTML 监控页面
 * </p>
 */
public class HtmlExporter {

    private static final String CSS =
            "<style>" +
                    "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }" +
                    ".container { max-width: 1200px; margin: 0 auto; }" +
                    "h1 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }" +
                    "h2 { color: #555; margin-top: 30px; }" +
                    ".nav { margin: 20px 0; }" +
                    ".nav a { margin-right: 15px; color: #007bff; text-decoration: none; }" +
                    ".nav a:hover { text-decoration: underline; }" +
                    "table { width: 100%; border-collapse: collapse; background: #fff; margin: 15px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }" +
                    "th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }" +
                    "th { background: #007bff; color: #fff; font-weight: 500; }" +
                    "tr:hover { background: #f8f9fa; }" +
                    ".metric-name { font-weight: 500; color: #333; }" +
                    ".metric-value { font-family: 'Monaco', 'Menlo', monospace; }" +
                    ".metric-desc { color: #888; font-size: 0.9em; }" +
                    ".category-badge { display: inline-block; padding: 3px 8px; border-radius: 3px; font-size: 0.8em; }" +
                    ".badge-jvm { background: #e3f2fd; color: #1976d2; }" +
                    ".badge-thread { background: #f3e5f5; color: #7b1fa2; }" +
                    ".badge-os { background: #e8f5e9; color: #388e3c; }" +
                    ".badge-custom { background: #fff3e0; color: #f57c00; }" +
                    ".footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 0.9em; }" +
                    ".refresh-hint { color: #666; font-size: 0.9em; }" +
                    ".summary { display: flex; gap: 20px; margin: 20px 0; }" +
                    ".summary-card { background: #fff; padding: 15px 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }" +
                    ".summary-card h3 { margin: 0 0 10px 0; color: #333; font-size: 0.9em; }" +
                    ".summary-card .value { font-size: 1.8em; font-weight: bold; color: #007bff; }" +
                    "</style>";

    private final MetricsRegistry registry;

    /**
     * HtmlExporter方法。
     * * @param registry MetricsRegistry类型参数
     */
    public HtmlExporter(MetricsRegistry registry) {
        this.registry = registry;
    }

    /**
     * export方法。
     *
     * @return String类型返回值
     */
    public String export() {
        List<MetricsSnapshot> snapshots = registry.collect();

        // 按分类分组
        Map<MetricsSnapshot.Category, List<MetricsSnapshot>> grouped = new TreeMap<>();
        for (MetricsSnapshot snapshot : snapshots) {
            grouped.computeIfAbsent(snapshot.getCategory(), k -> new java.util.ArrayList<>()).add(snapshot);
        }

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"zh-CN\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <title>Z-Util Monitor</title>\n");
        html.append(CSS);
        html.append("</head>\n");
        html.append("<body>\n");
        html.append("    <div class=\"container\">\n");

        // 标题和导航
        html.append("        <h1>Z-Util Monitor</h1>\n");
        html.append("        <div class=\"nav\">\n");
        html.append("            <a href=\"/\">首页</a>\n");
        html.append("            <a href=\"/json\">JSON</a>\n");
        html.append("            <a href=\"/health\">健康检查</a>\n");
        html.append("        </div>\n");
        html.append("        <p class=\"refresh-hint\">页面将于 30 秒后自动刷新</p>\n");

        // 概览卡片
        html.append(exportSummaryCards(grouped));

        // 各类别指标表格
        for (Map.Entry<MetricsSnapshot.Category, List<MetricsSnapshot>> entry : grouped.entrySet()) {
            html.append(exportCategoryTable(entry.getKey(), entry.getValue()));
        }

        // 页脚
        html.append("        <div class=\"footer\">\n");
        html.append("            <p>Generated by Z-Util Monitor at ")
                .append(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()))
                .append("</p>\n");
        html.append("        </div>\n");

        html.append("    </div>\n");
        html.append("    <script>setTimeout(() => location.reload(), 30000);</script>\n");
        html.append("</body>\n");
        html.append("</html>");

        return html.toString();
    }

    private String exportSummaryCards(Map<MetricsSnapshot.Category, List<MetricsSnapshot>> grouped) {
        StringBuilder sb = new StringBuilder();
        sb.append("        <div class=\"summary\">\n");

        // 总指标数
        int totalCount = grouped.values().stream().mapToInt(List::size).sum();
        sb.append("            <div class=\"summary-card\">\n");
        sb.append("                <h3>总指标数</h3>\n");
        sb.append("                <div class=\"value\">").append(totalCount).append("</div>\n");
        sb.append("            </div>\n");

        // 各类别数量
        for (MetricsSnapshot.Category category : MetricsSnapshot.Category.values()) {
            int count = grouped.getOrDefault(category, Lists.of()).size();
            sb.append("            <div class=\"summary-card\">\n");
            sb.append("                <h3>").append(category.getLabel()).append("</h3>\n");
            sb.append("                <div class=\"value\">").append(count).append("</div>\n");
            sb.append("            </div>\n");
        }

        sb.append("        </div>\n");
        return sb.toString();
    }

    private String exportCategoryTable(MetricsSnapshot.Category category, List<MetricsSnapshot> snapshots) {
        StringBuilder sb = new StringBuilder();
        sb.append("        <h2>").append(category.getLabel()).append("</h2>\n");
        sb.append("        <table>\n");
        sb.append("            <thead>\n");
        sb.append("                <tr>\n");
        sb.append("                    <th>指标名称</th>\n");
        sb.append("                    <th>值</th>\n");
        sb.append("                    <th>单位</th>\n");
        sb.append("                    <th>描述</th>\n");
        sb.append("                </tr>\n");
        sb.append("            </thead>\n");
        sb.append("            <tbody>\n");

        for (MetricsSnapshot snapshot : snapshots) {
            sb.append("                <tr>\n");
            sb.append("                    <td class=\"metric-name\">").append(escapeHtml(snapshot.getName())).append("</td>\n");
            sb.append("                    <td class=\"metric-value\">").append(formatValue(snapshot)).append("</td>\n");
            sb.append("                    <td>").append(snapshot.getUnit() != null ? escapeHtml(snapshot.getUnit()) : "-").append("</td>\n");
            sb.append("                    <td class=\"metric-desc\">").append(snapshot.getDescription() != null ? escapeHtml(snapshot.getDescription()) : "-").append("</td>\n");
            sb.append("                </tr>\n");
        }

        sb.append("            </tbody>\n");
        sb.append("        </table>\n");
        return sb.toString();
    }

    private String formatValue(MetricsSnapshot snapshot) {
        Object value = snapshot.getValue();
        if (value == null) {
            return "-";
        }

        String str = value.toString();

        // 格式化字节单位
        if (value instanceof Number && snapshot.getUnit() != null && snapshot.getUnit().equals("bytes")) {
            long bytes = ((Number) value).longValue();
            if (bytes >= 0) {
                return formatBytes(bytes) + " (" + str + ")";
            }
        }

        // 格式化时间单位 (ms)
        if (value instanceof Number && snapshot.getUnit() != null && snapshot.getUnit().equals("ms")) {
            long ms = ((Number) value).longValue();
            if (ms >= 0) {
                return formatDuration(ms) + " (" + str + " ms)";
            }
        }

        return escapeHtml(str);
    }

    private String formatBytes(long bytes) {
        if (bytes < 0) {
            return "N/A";
        }
        if (bytes < 1024) {
            return bytes + " B";
        }
        if (bytes < 1024 * 1024) {
            return String.format("%.2f KB", bytes / 1024.0);
        }
        if (bytes < 1024 * 1024 * 1024) {
            return String.format("%.2f MB", bytes / (1024.0 * 1024));
        }
        return String.format("%.2f GB", bytes / (1024.0 * 1024 * 1024));
    }

    private String formatDuration(long ms) {
        if (ms < 1000) {
            return ms + " ms";
        }
        if (ms < 60 * 1000) {
            return String.format("%.2f s", ms / 1000.0);
        }
        if (ms < 60 * 60 * 1000) {
            return String.format("%.2f min", ms / (60.0 * 1000));
        }
        return String.format("%.2f h", ms / (60.0 * 60 * 1000));
    }

    private String escapeHtml(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
