<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.yuku123</groupId>
        <artifactId>z-util</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>z-util-cli</artifactId>
    <packaging>jar</packaging>

    <name>z-util :: cli (POSIX/GNU/Basic/Default CLI parser + OptionGroup + HelpFormatter)</name>
    <description>Command line parsing and help formatting, full coverage of Apache Commons CLI capabilities
    </description>

    <dependencies>
        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
